import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, Animated, ImageBackground, Linking, PanResponder, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { completeOAuthRedirect, friendlyError, loadViennaDiscoveryDeck, newRequestId, persistSwipe, signIn, type DiscoveryRestaurant, type SignInProvider } from '../lib/catalogue';

const C = { ink:'#201A17', coral:'#B52640', cream:'#FFF9F5' };
const previewLimit = 2;
export default function Discovery() {
  const [restaurants, setRestaurants] = useState<DiscoveryRestaurant[]>([]), [user, setUser] = useState<{id:string}|null>(null), [state, setState] = useState<'loading'|'ready'|'error'>('loading'), [authOpen, setAuthOpen] = useState(false), [infoOpen, setInfoOpen] = useState(false), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false);
  const x = useRef(new Animated.Value(0)).current, lock = useRef(false), previewed = useRef(new Set<string>());
  const restaurant = restaurants[0];
  const load = useCallback(async () => { setState('loading'); try { const deck = await loadViennaDiscoveryDeck(); setRestaurants(deck.restaurants.filter((place) => !previewed.current.has(place.id))); setUser(deck.user); if (deck.user) { setAuthOpen(false); setBusy(false); } setState('ready'); } catch (error) { setNotice(friendlyError(error)); setState('error'); } }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => {
    const finish = async (url:string|null) => { if (!url?.startsWith('shehungry://auth')) return; try { await completeOAuthRedirect(url); await load(); } catch (error) { setNotice(friendlyError(error)); setAuthOpen(true); } };
    void Linking.getInitialURL().then(finish); const listener = Linking.addEventListener('url', ({url}) => { void finish(url); }); return () => listener.remove();
  }, [load]);
  const decide = useCallback(async (liked:boolean) => {
    if (!restaurant || lock.current) return;
    if (!user) { if (previewed.current.size >= previewLimit) { setAuthOpen(true); return; } previewed.current.add(restaurant.id); setRestaurants((current) => current.filter((place) => place.id !== restaurant.id)); return; }
    lock.current = true; setBusy(true); setNotice(''); x.setValue(0);
    try { await persistSwipe(restaurant.id, liked ? 'like' : 'skip', newRequestId()); setRestaurants((current) => current.filter((place) => place.id !== restaurant.id)); } catch (error) { setNotice(friendlyError(error)); } finally { lock.current = false; setBusy(false); }
  }, [restaurant, user, x]);
  const pan = useMemo(() => PanResponder.create({
    onMoveShouldSetPanResponder:(_, gesture) => !lock.current && !authOpen && (Math.abs(gesture.dx) > 10 || Math.abs(gesture.dy) > 10),
    onPanResponderMove:(_, gesture) => { if (!lock.current && Math.abs(gesture.dx) > Math.abs(gesture.dy)) x.setValue(gesture.dx); },
    onPanResponderRelease:(_, gesture) => { x.setValue(0); if (gesture.dy < -100 && Math.abs(gesture.dy) > Math.abs(gesture.dx)) { setInfoOpen(true); return; } if (Math.abs(gesture.dx) > 100 && Math.abs(gesture.dx) > Math.abs(gesture.dy)) void decide(gesture.dx > 0); },
    onPanResponderTerminate:() => x.setValue(0),
  }), [authOpen, decide, x]);
  const infoPan = useMemo(() => PanResponder.create({ onMoveShouldSetPanResponder:(_, gesture) => gesture.dy > 10, onPanResponderRelease:(_, gesture) => { if (gesture.dy > 70) setInfoOpen(false); } }), []);
  async function authenticate(provider:SignInProvider) { setBusy(true); setNotice(''); try { await signIn(provider); } catch (error) { setNotice(friendlyError(error)); setBusy(false); } }
  if (state === 'loading') return <SafeAreaView style={s.state}><ActivityIndicator color={C.coral} accessibilityLabel="Finding a good table" /></SafeAreaView>;
  if (state === 'error' || !restaurant) return <SafeAreaView style={s.state}><Text style={s.stateText}>{notice || 'No more picks right now.'}</Text></SafeAreaView>;
  const cardContent = <><View style={s.shade}/><View style={s.copy}><Text style={s.neighbourhood}>{restaurant.neighbourhood}</Text><Text style={s.name}>{restaurant.name}</Text><Text style={s.cuisine}>{restaurant.cuisine}</Text></View></>;
  return <SafeAreaView style={s.screen}><Animated.View {...pan.panHandlers} style={[s.card,{transform:[{translateX:x}]}]}>{restaurant.imageUrl ? <ImageBackground source={{uri:restaurant.imageUrl}} style={s.image}>{cardContent}</ImageBackground> : <View style={[s.image,s.art]}>{cardContent}</View>}</Animated.View>{notice ? <Text style={s.notice} accessibilityRole="alert">{notice}</Text> : null}{infoOpen ? <View {...infoPan.panHandlers} style={s.info}><View style={s.handle}/><Text style={s.infoNeighbourhood}>{restaurant.neighbourhood}</Text><Text style={s.infoName}>{restaurant.name}</Text><Text style={s.infoCuisine}>{restaurant.cuisine}</Text><Text style={s.infoText}>{restaurant.description}</Text>{restaurant.address ? <Text style={s.address}>{restaurant.address}</Text> : null}</View> : null}{authOpen ? <View style={s.gate}><View style={s.gateCard}><Text style={s.logo}>she<Text style={{color:C.coral}}>hungry</Text></Text><Text style={s.gateTitle}>Keep discovering.</Text><Text style={s.gateText}>Sign in to make every next swipe yours.</Text><Pressable disabled={busy} style={s.google} onPress={() => void authenticate('google')}><Text style={s.googleText}>G   Continue with Google</Text></Pressable><Pressable disabled={busy} style={s.apple} onPress={() => void authenticate('apple')}><Text style={s.appleText}>   Continue with Apple</Text></Pressable></View></View> : null}</SafeAreaView>;
}
const s = StyleSheet.create({
  screen:{ flex:1, backgroundColor:'#241715' }, state:{ flex:1, alignItems:'center', justifyContent:'center', backgroundColor:C.cream, padding:30 }, stateText:{ color:C.ink, fontSize:17, textAlign:'center' }, card:{ position:'absolute', top:0, right:0, bottom:0, left:0, overflow:'hidden' }, image:{ flex:1, justifyContent:'flex-end' }, art:{ backgroundColor:'#9d4437' }, shade:{ position:'absolute', top:0, right:0, bottom:0, left:0, backgroundColor:'rgba(20,12,10,.48)' }, copy:{ padding:28, paddingBottom:42 }, neighbourhood:{ color:'#fff', fontSize:12, fontWeight:'800', letterSpacing:1.2 }, name:{ marginTop:6, color:'#fff', fontFamily:'Georgia', fontSize:54, fontWeight:'700', letterSpacing:-3, lineHeight:55 }, cuisine:{ marginTop:13, color:'#fff', fontSize:15, fontWeight:'700' }, notice:{ position:'absolute', top:18, right:18, left:18, borderRadius:14, padding:12, backgroundColor:'#FFF0E6', color:C.ink, textAlign:'center' }, info:{ position:'absolute', right:0, bottom:0, left:0, maxHeight:'48%', overflow:'hidden', borderTopLeftRadius:28, borderTopRightRadius:28, backgroundColor:C.cream, paddingHorizontal:28, paddingBottom:40 }, handle:{ width:38, height:4, alignSelf:'center', marginVertical:12, borderRadius:3, backgroundColor:'#C7BBB4' }, infoNeighbourhood:{ color:'#756A64', fontSize:12, fontWeight:'800', letterSpacing:1.2 }, infoName:{ marginTop:6, color:C.ink, fontFamily:'Georgia', fontSize:38, fontWeight:'700', letterSpacing:-2 }, infoCuisine:{ marginTop:7, color:C.ink, fontWeight:'800' }, infoText:{ marginTop:14, color:'#756A64', lineHeight:21 }, address:{ marginTop:14, color:'#756A64', fontSize:13 }, gate:{ position:'absolute', top:0, right:0, bottom:0, left:0, alignItems:'center', justifyContent:'center', padding:28, backgroundColor:'rgba(20,12,10,.72)' }, gateCard:{ width:'100%', maxWidth:350, borderRadius:28, padding:26, backgroundColor:C.cream, alignItems:'center' }, logo:{ marginBottom:38, color:C.ink, fontFamily:'Georgia', fontSize:28, fontWeight:'800', letterSpacing:-1 }, gateTitle:{ color:C.ink, fontFamily:'Georgia', fontSize:34, fontWeight:'700', letterSpacing:-1.2 }, gateText:{ marginTop:11, marginBottom:20, color:'#756A64', fontSize:15, lineHeight:21, textAlign:'center' }, google:{ width:'100%', marginVertical:5, borderWidth:1, borderColor:'#D8D1CC', borderRadius:12, backgroundColor:'#fff', padding:14, alignItems:'center' }, googleText:{ color:C.ink, fontWeight:'800' }, apple:{ width:'100%', marginVertical:5, borderRadius:12, backgroundColor:'#111', padding:15, alignItems:'center' }, appleText:{ color:'#fff', fontWeight:'800' },
});
