import { useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context';
import { StatusBar } from 'expo-status-bar';
import * as Linking from 'expo-linking';
import { restaurants } from '@shehungry/core';
import { completeAuthRedirect, currentUser, sendMagicLink, signOut, watchAuth } from './lib/auth';

type Viewer = { label: string } | null;

function App() {
  const [index, setIndex] = useState(0), [saved, setSaved] = useState<string[]>([]), [viewer, setViewer] = useState<Viewer>(null), [authOpen, setAuthOpen] = useState(false), [email, setEmail] = useState('');
  const restaurant = restaurants[index];
  const savedRestaurants = useMemo(() => restaurants.filter((item) => saved.includes(item.id)), [saved]);
  useEffect(() => {
    void currentUser().then((user) => user && setViewer({ label: user.email ?? 'Signed in' }));
    void Linking.getInitialURL().then((url) => { if (url) void completeAuthRedirect(url); });
    const link = Linking.addEventListener('url', ({ url }) => { void completeAuthRedirect(url); });
    const unsubscribe = watchAuth((user) => setViewer(user ? { label: user.email ?? 'Signed in' } : null));
    return () => { link.remove(); unsubscribe(); };
  }, []);
  function next() { setIndex((value) => (value + 1) % restaurants.length); }
  function save() { if (!viewer) { setAuthOpen(true); return; } setSaved((value) => value.includes(restaurant.id) ? value.filter((id) => id !== restaurant.id) : [...value, restaurant.id]); }
  async function requestLink() { try { await sendMagicLink(email); Alert.alert('Check your inbox', 'Your sign-in link is on its way.'); } catch (error) { Alert.alert('Sign-in unavailable', error instanceof Error ? error.message : 'Please try again.'); } }
  return <SafeAreaView style={styles.screen}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Text style={styles.brand}>she<Text style={styles.coral}>hungry</Text></Text><Pressable onPress={() => viewer ? void signOut() : setAuthOpen(true)}><Text style={styles.account}>{viewer ? 'Sign out' : 'Sign in'}</Text></Pressable></View><Text style={styles.eyebrow}>VIENNA · DEMO CATALOGUE</Text><Text style={styles.hero}>What are you hungry for?</Text><Text style={styles.subhead}>Twenty fictional places, ready for the product before real data arrives.</Text><View style={styles.card}><View style={styles.cardTop}><Text style={styles.light}>{restaurant.price}</Text><Text style={styles.light}>{index + 1} / {restaurants.length}</Text></View><View style={styles.orb}><Text style={styles.star}>✦</Text></View><Text style={styles.light}>{restaurant.neighbourhood.toUpperCase()}</Text><Text style={styles.name}>{restaurant.name}</Text><Text style={styles.cuisine}>{restaurant.cuisine}</Text><Text style={styles.description}>{restaurant.description}</Text><Text style={styles.try}>TRY</Text><Text style={styles.dish}>{restaurant.signatureDish}</Text><View style={styles.tags}>{restaurant.tags.map((tag) => <Text key={tag} style={styles.tag}>{tag}</Text>)}</View><View style={styles.actions}><Pressable style={styles.secondary} onPress={next}><Text style={styles.secondaryText}>Not now</Text></Pressable><Pressable style={styles.primary} onPress={save}><Text style={styles.primaryText}>{saved.includes(restaurant.id) ? 'Saved ✓' : 'Save place'}</Text></Pressable></View></View>{savedRestaurants.length > 0 && <View style={styles.saved}><Text style={styles.eyebrow}>YOUR LIST</Text><Text style={styles.savedTitle}>Saved for later</Text>{savedRestaurants.map((item) => <Pressable key={item.id} style={styles.savedItem} onPress={() => setIndex(restaurants.indexOf(item))}><Text style={styles.savedName}>{item.name}</Text><Text style={styles.savedCuisine}>{item.cuisine}</Text></Pressable>)}</View>}</ScrollView>{authOpen && <View style={styles.overlay}><View style={styles.modal}><Pressable style={styles.close} onPress={() => setAuthOpen(false)}><Text style={styles.closeText}>×</Text></Pressable><Text style={styles.eyebrow}>YOUR SHEHUNGRY ACCOUNT</Text><Text style={styles.modalTitle}>Save your next bite.</Text><Text style={styles.modalText}>Enter your email and we’ll send a secure sign-in link.</Text><TextInput autoCapitalize="none" autoComplete="email" keyboardType="email-address" placeholder="you@example.com" style={styles.input} value={email} onChangeText={setEmail}/><Pressable style={styles.primary} onPress={() => void requestLink()}><Text style={styles.primaryText}>Send sign-in link</Text></Pressable><Pressable onPress={() => { setViewer({ label: 'Demo guest' }); setAuthOpen(false); }}><Text style={styles.demo}>Continue in demo mode</Text></Pressable></View></View>}</SafeAreaView>;
}

export default function Root() { return <SafeAreaProvider><StatusBar style="dark"/><App /></SafeAreaProvider>; }

const styles = StyleSheet.create({
  screen:{flex:1,backgroundColor:'#fff7ef'},content:{padding:20,paddingBottom:50},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:56},brand:{fontFamily:'Georgia',fontSize:28,fontWeight:'800',letterSpacing:-1.5,color:'#211b19'},coral:{color:'#d94f4f'},account:{color:'#315e53',fontWeight:'700'},eyebrow:{color:'#315e53',fontSize:11,fontWeight:'800',letterSpacing:1.2},hero:{marginTop:10,fontFamily:'Georgia',fontSize:51,fontWeight:'700',letterSpacing:-2.8,lineHeight:48,color:'#211b19'},subhead:{maxWidth:330,marginTop:18,marginBottom:30,color:'#635953',fontSize:16,lineHeight:23},card:{borderRadius:30,backgroundColor:'#315e53',padding:24},cardTop:{flexDirection:'row',justifyContent:'space-between'},light:{color:'#cce5d5',fontSize:12,fontWeight:'800',letterSpacing:1.1},orb:{width:105,height:105,alignSelf:'flex-end',alignItems:'center',justifyContent:'center',marginVertical:40,borderRadius:100,backgroundColor:'#ff986e'},star:{color:'#fff',fontSize:34},name:{marginTop:7,fontFamily:'Georgia',fontSize:49,fontWeight:'700',letterSpacing:-2.7,lineHeight:47,color:'#fff'},cuisine:{marginTop:10,color:'#ffd4bd',fontWeight:'800'},description:{marginTop:18,color:'#fff',fontSize:15,lineHeight:22},try:{marginTop:22,color:'#cce5d5',fontSize:11,fontWeight:'800',letterSpacing:1.1},dish:{marginTop:4,color:'#fff',fontSize:18,fontWeight:'800'},tags:{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:15},tag:{borderWidth:1,borderColor:'rgba(255,255,255,.4)',borderRadius:20,paddingHorizontal:10,paddingVertical:6,color:'#fff',fontSize:11},actions:{flexDirection:'row',gap:9,marginTop:28},primary:{flex:1,alignItems:'center',borderRadius:50,backgroundColor:'#d94f4f',padding:14},secondary:{flex:1,alignItems:'center',borderRadius:50,backgroundColor:'#fff',padding:14},primaryText:{color:'#fff',fontWeight:'800'},secondaryText:{color:'#211b19',fontWeight:'800'},saved:{marginTop:42},savedTitle:{marginTop:8,fontFamily:'Georgia',fontSize:35,fontWeight:'700',letterSpacing:-1.8,color:'#211b19'},savedItem:{paddingVertical:16,borderBottomWidth:1,borderBottomColor:'#e4cec0'},savedName:{fontWeight:'800',color:'#211b19'},savedCuisine:{marginTop:4,color:'#806f68'},overlay:{position:'absolute',top:0,right:0,bottom:0,left:0,alignItems:'center',justifyContent:'center',padding:20,backgroundColor:'rgba(27,22,19,.45)'},modal:{position:'relative',width:'100%',borderRadius:28,backgroundColor:'#fffaf5',padding:30},close:{position:'absolute',top:10,right:16},closeText:{fontSize:30,color:'#315e53'},modalTitle:{marginTop:11,fontFamily:'Georgia',fontSize:43,fontWeight:'700',letterSpacing:-2.2,lineHeight:41,color:'#211b19'},modalText:{marginVertical:16,color:'#635953',lineHeight:21},input:{marginBottom:12,borderWidth:1,borderColor:'#ccbdb4',borderRadius:10,padding:13,backgroundColor:'#fff'},demo:{marginTop:18,color:'#315e53',textAlign:'center',textDecorationLine:'underline'}
});
